manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/Ahmed-M-Osman1/zmk-azoteq
    - name: urob
      url-base: https://github.com/urob
  projects:
    - name: zmk
      remote: urob
      revision: main-with-native-mouse
      import: app/west.yml
  self:
    path: config
