manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com
  projects:
    - name: zmk
      revision: main
      clone-depth: 1
      url: https://github.com/Ahmed-M-Osman1/zmk-azoteq
      import: app/west.yml
  self:
    path: config
